<!DOCTYPE html>
<html>
<head>ANNOUNCEMENT</head>
<body>
<h1>ANNOUNCEMENT</h1>
<h4>Create announcement</h4>
<form action="/form-create" method="post">
    Title:          <input type="text" name="title"/><br><br>
    Address:        <input type="text" name="address"/><br><br>
    Price:          <input type="number" name="price"/><br><br>
    Number Of Beds: <input type="number" name="numberOfBeds"/><br><br>
    Description:    <input type="text" name="description"/><br><br>
    <input type="submit" value="add">
</form>
</body>
</html>